name             'cheflab'
maintainer       'Scott Ford'
maintainer_email 'fords@chef.io'
license          'Apache 2.0'
description      'Installs/Configures cheflab'
long_description 'Installs/Configures cheflab'
version          '0.1.0'

depends 'chef-server12'
depends 'git'
depends 'java'
depends 'sudo'
depends 'jenkins'
depends 'chef-dk'
depends 'gitlab'

